"""Public interface for the tool-neutral IGOR core module."""

from igor_core.canonical import canonical_json, stable_identity
from igor_core.contracts import (
    ArtifactIndex,
    ArtifactReference,
    ProducerIdentity,
    RunIdentityLinks,
    RunManifest,
    RunPackage,
    StageResult,
    validate_run_directory,
)
from igor_core.lineage import LineageEdge, LineageGraph, LineageNode, LineagePresentation
from igor_core.profiles import (
    CompilerProfile,
    ModelProfile,
    ReferenceProfile,
    load_model_profile,
    load_reference_profile,
)
from igor_core.semantic import (
    ConnectorBinding,
    ConnectorFieldBinding,
    ConnectorResourceBinding,
    ContentPart,
    ContextSourceContract,
    ContextItem,
    ContextPackage,
    Derivation,
    Embedding,
    EmbeddingSpace,
    EnrichmentRecipe,
    EnrichmentOutput,
    Evidence,
    Representation,
    SchemaDescriptor,
    SchemaField,
    SourceFieldRequirement,
    SourceResourceContract,
    SourceSnapshot,
    affected_outputs,
    validate_context_artifact,
    validate_schema_payload,
)

__all__ = [
    "CompilerProfile",
    "ModelProfile",
    "ReferenceProfile",
    "ArtifactIndex",
    "ArtifactReference",
    "ProducerIdentity",
    "RunIdentityLinks",
    "RunManifest",
    "RunPackage",
    "StageResult",
    "canonical_json",
    "load_reference_profile",
    "load_model_profile",
    "stable_identity",
    "validate_run_directory",
    "LineageEdge",
    "LineageGraph",
    "LineageNode",
    "LineagePresentation",
    "ConnectorBinding",
    "ConnectorFieldBinding",
    "ConnectorResourceBinding",
    "ContentPart",
    "ContextSourceContract",
    "SchemaField",
    "SchemaDescriptor",
    "SourceFieldRequirement",
    "SourceResourceContract",
    "SourceSnapshot",
    "Representation",
    "Evidence",
    "Derivation",
    "EmbeddingSpace",
    "Embedding",
    "EnrichmentOutput",
    "EnrichmentRecipe",
    "ContextItem",
    "ContextPackage",
    "affected_outputs",
    "validate_context_artifact",
    "validate_schema_payload",
]
